name: Checks

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Check JavaScript syntax
        run: git ls-files -z '*.js' | xargs -0 -n1 node --check
      - run: npm test
